#!/bin/bash
#
# vim:ft=sh

############### Variables ###############

############### Functions ###############

############### Main Part ###############
echo $PWD
echo ok
bin/console doc:mig:mig -n
